#ifndef OPENMW_WEBCUDA_FOGTEXTURE_H
#define OPENMW_WEBCUDA_FOGTEXTURE_H
#include "materialstate.hpp"
#include <components/esm3/fogstate.hpp>
#include <osg/Texture2D>
#include <array>
#include <algorithm>
#include <set>
#include <cstring>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace WebCuda {
class FogTexture final : public osg::Texture2D {
public:
    explicit FogTexture(const osg::Image& image) { reset(image); }
    FogTexture(const FogTexture& other,const osg::CopyOp& copy=osg::CopyOp::SHALLOW_COPY)
        : osg::Texture2D(other,copy),saved(other.saved),brushes(other.brushes),revision(other.revision),mKnownBrushes(other.mKnownBrushes) {}
    osg::Object* cloneType() const override { return new FogTexture(*this); }
    osg::Object* clone(const osg::CopyOp& copy) const override { return new FogTexture(*this,copy); }
    void reset(const osg::Image& image) {
        saved=copyTexturePixels(image).rgba;brushes.clear();mKnownBrushes.clear();saveSnapshot.reset();compactionRequest.reset();++revision;
        setTextureSize(image.s(),image.t());setInternalFormat(GL_RGBA8);
    }
    void restoreSnapshot(const ESM::PendingFogImage& snapshot) {
        const std::uint64_t count=std::uint64_t(snapshot.mWidth)*snapshot.mHeight;
        if(!snapshot.mWidth||!snapshot.mHeight||snapshot.mWidth>std::numeric_limits<int>::max()||snapshot.mHeight>std::numeric_limits<int>::max()
            ||snapshot.mInputs.empty()||snapshot.mInputs.size()!=1u+count+std::uint64_t(snapshot.mInputs[0])*3u)
            throw std::runtime_error("Invalid retained fog snapshot");
        saved.assign(snapshot.mInputs.begin()+1,snapshot.mInputs.begin()+1+count);
        brushes.clear();mKnownBrushes.clear();saveSnapshot.reset();compactionRequest.reset();
        setTextureSize(snapshot.mWidth,snapshot.mHeight);
        for(std::size_t offset=1u+count;offset<snapshot.mInputs.size();offset+=3u) {
            float values[3];std::memcpy(values,snapshot.mInputs.data()+offset,12);
            explore(values[0],values[1],values[2]);
        }
        ++revision;
    }
    void explore(float x,float y,float radiusSquared) {
        if(!std::isfinite(x)||!std::isfinite(y)||!std::isfinite(radiusSquared)||radiusSquared<=0)
            throw std::runtime_error("Invalid fog exploration brush");
        const std::array<float,3> brush{x,y,radiusSquared};
        if(mKnownBrushes.find(brush)!=mKnownBrushes.end())return;
        if(brushes.size()>=std::numeric_limits<unsigned int>::max()/3u)throw std::runtime_error("Fog brush history overflow");
        brushes.push_back(brush);mKnownBrushes.insert(brush);saveSnapshot.reset();++revision;
    }
    bool needsCompaction() const {
        const auto pending=compactionRequest.lock();
        return brushes.size()>=256u&&(!pending||pending->mReady);
    }
    void compact(const std::shared_ptr<ESM::PendingFogImage>& snapshot,const osg::Image& image) {
        if(snapshot->mWidth!=static_cast<unsigned int>(getTextureWidth())||snapshot->mHeight!=static_cast<unsigned int>(getTextureHeight())
            ||snapshot->mInputs.empty()||image.s()!=getTextureWidth()||image.t()!=getTextureHeight())return;
        const auto count=snapshot->mInputs[0];
        if(count>brushes.size()||snapshot->mInputs.size()!=1u+saved.size()+std::size_t(count)*3u
            ||!std::equal(saved.begin(),saved.end(),snapshot->mInputs.begin()+1))return;
        // Accept only an unchanged baseline and an exact brush prefix. A reset,
        // reload or newer completed snapshot makes this result obsolete.
        for(std::size_t b=0;b<count;b++)for(unsigned int k=0;k<3;k++) {
            unsigned int bits;std::memcpy(&bits,&brushes[b][k],4);
            if(bits!=snapshot->mInputs[1u+saved.size()+b*3u+k])return;
        }
        saved=copyTexturePixels(image).rgba;
        brushes.erase(brushes.begin(),brushes.begin()+count);
        mKnownBrushes.clear();for(const auto& brush:brushes)mKnownBrushes.insert(brush);
        ++revision;
        if(brushes.empty())saveSnapshot=snapshot;
    }
    std::vector<unsigned int> captureInputs() const {
        std::vector<unsigned int> result;
        result.reserve(1+saved.size()+brushes.size()*3);
        result.push_back(static_cast<unsigned int>(brushes.size()));
        result.insert(result.end(),saved.begin(),saved.end());
        for(const auto& brush:brushes)for(float value:brush) {
            unsigned int bits;std::memcpy(&bits,&value,4);result.push_back(bits);
        }
        return result;
    }
    // A gameplay point query, not an image renderer. The displayed image is
    // generated by generate_fog_map using the same saved mask and brush inputs.
    bool isExplored(unsigned int x,unsigned int y) const {
        const auto width=static_cast<unsigned int>(getTextureWidth());
        if(x>=width||y>=static_cast<unsigned int>(getTextureHeight()))return false;
        const auto index=static_cast<std::size_t>(y)*width+x;
        if(index>=saved.size())throw std::runtime_error("Invalid saved fog extent");
        if((saved[index]>>24u)<200u)return true;
        for(const auto& brush:brushes) {
            const float dx=static_cast<float>(x)-brush[0],dy=static_cast<float>(y)-brush[1];
            const auto alpha=static_cast<unsigned int>(std::clamp((dx*dx+dy*dy)/brush[2],0.f,1.f)*255.f);
            if(alpha<200u)return true;
        }
        return false;
    }
    std::vector<std::uint32_t> saved;
    std::vector<std::array<float,3>> brushes;
    std::uint64_t revision=0;
    mutable std::shared_ptr<ESM::PendingFogImage> saveSnapshot;
    mutable std::weak_ptr<ESM::PendingFogImage> compactionRequest;
private:
    std::set<std::array<float,3>> mKnownBrushes;
};
}
#endif
